.\" Manpage for twodrc.
.\" Contact tablet-mode@monochromatic.cc to correct errors or typos.
.TH twodrc 5 "19 March 2014" "twod 0.2.0" "twod man page"
.SH NAME
\fBtwodrc\fR - \fBtwod\fR twodns.de host updater daemon configuration files
.SH SYNOPSIS
.BR /etc/twod/twodrc
.SH DESCRIPTION
twod(8) looks for configuration data in the following path:
.IP
/etc/twod/twodrc
.SH CONFIGURATION VARIABLES
Valid configuration variables:
.SS "GENERAL SECTION"
.TP
.B "user"
.br
Name of the twodns.de account.
.br
.TP
.B "token"
.br
Token for the twodns.de account.
.br
.TP
.B "host_url"
.br
URL of the twodns.de host.
.br
.TP
.B interval
.br
Update interval in seconds.
.TP
.B timeout
.br
Timeout for retrieving and setting your external IP, in seconds.
.SS "IP_SERVICE SECTION"
.TP
.B "mode"
.br
Sets the method of selecting the URL used to retrieve current external IP.
.br
Possible values:
.P
            random        Selects a random URL from list.
.br
            round_robin   Cycles through URLs in sequence.
.TP
.B "ip_urls"
.br
List of URLs used to query external IP.
.SS "LOGGING SECTION"
.TP
.B "level"
.br
Log level.
.SH SEE ALSO
twod(8)
.SH FILES
/etc/twod/twodrc
       Contains configuration data for twod(8). This file should be writable
       by root only, but it is recommended (though not necessary) that it be
       world-readable.
.SH AUTHOR
Tablet Mode <tablet-mode@monochromatic.cc>
