.\" Manpage for twod.
.\" Contact tablet-mode@monochromatic.cc to correct errors or typos.
.TH twod 8 "1 October 2015" "twod 0.4.0" "twod man page"
.SH NAME
\fBtwod\fR - update twodns.de hosts
.SH SYNOPSIS
\fBtwod\fR [options]
.SH DESCRIPTION
\fBtwod\fR is a daemon for updating twodns.de hosts.
.SH OPTIONS
.TP
.B "--help (-h)"
Print the usage and exit.
.TP
.B "--config (-c)"
Specifies the name of the configuration file. The default is /etc/twod/twodrc.
.TP
.B "--pidfile (-p)"
Specifies the path of the pidfile to use. The default is /var/run/twod.pid.
.TP
.B "--no-detach (-D)"
Do not detach and run in foreground instead.
.TP
.B "--version (-V)"
Display version number and exit.
.SH FILES
/etc/twod/twodrc
       Contains configuration data for \fBtwod\fR. The file format and configuration
       options are described in twodrc(5).

/var/run/twod.pid
       Contains the process ID of \fBtwod\fR.
.SH SEE ALSO
twodrc(5)
.SH BUGS
No known bugs.
.SH AUTHOR
Tablet Mode <tablet-mode@monochromatic.cc>
