.\" Manpage for twod.
.\" Contact tablet-mode@monochromatic.cc to correct errors or typos.
.TH twod 1 "19 March 2014" "twod 0.2.0" "twod man page"
.SH NAME
twod - update twodns.de hosts
.SH SYNOPSIS
twod [options]
.SH DESCRIPTION
twod is a daemon for updating twodns.de hosts.
.SH OPTIONS
.TP
.B "--config (-c)" 
Specifies the name of the configuration file. The default is /etc/twod/twodrc.
.SH SEE ALSO
twodrc(5)
.SH BUGS
No known bugs.
.SH AUTHOR
Tablet Mode <tablet-mode@monochromatic.cc>
